### ISSUE TITLE
Multiple pictures in project or news page

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#38] opened 2015-02-11 23:06 UTC
In Safari Version 7.1.2 (9537.85.11.5), Under Mac OsX 10.9.5, I end up with the backwards and forwards buttons in the picture image. 
Is this known a problem?
![screen shot 2015-02-11 at 23 52 58](https://cloud.githubusercontent.com/assets/3668316/6158470/e771a834-b24a-11e4-80a9-33e08244f82e.png)

**Comment by HexeBianca** [comment] 2015-02-12 12:03
I am using Firefox on a Windows Mashine. The poistion of the buttons changes with a simple reload of the page, which is strange...
![1](https://cloud.githubusercontent.com/assets/10153723/6167058/55fdda68-b2b7-11e4-8b42-941e98d737b2.jpg)
![2](https://cloud.githubusercontent.com/assets/10153723/6167059/560b8500-b2b7-11e4-8122-17ecfc9b9acf.jpg)

**Comment by elondaits** [comment] 2015-02-12 12:47
Most likely the buttons are placed by a script before the image is fully loaded, when it's height is zero, so they're placed at the top... Once you reload the image is loaded from cache, which is much faster, so the buttons get placed correctly.

This could be related to a bug @christophknoth was working on related to images having their dimensions in the IMG element (which would remove the issue if the cause above is right).

If that is not possible it could *probably* be solved by having the buttons have an absolute placement relative to the IMG (position: absolute; bottom: 0px; margin-bottom: -40px // aproximate). In this case I could help with this.

**Comment by ppxasjsm** [comment] 2015-02-12 21:58
I observe the same reload behaviour in Safari.

**Comment by christophknoth** [comment] 2015-03-13 11:59
I guess this might be solved with an imagesloaded callback around the generation of the gallery in the main.js. I have to check.

**Comment by konrad-renner** [comment] 2015-04-13 12:12
here you can see the problem: 
http://imaginary.org/content/imaginary-israel

**Comment by christophknoth** [comment] 2015-04-20 10:31
Should be hopefully fixed with the latest commit.

**Closed by christophknoth** 2015-04-20 10:31 UTC
Labels: bug, high priority

**Comment by HexeBianca** [comment] 2015-04-20 10:38
:thumbsup:
