### ISSUE TITLE
Snapshot translations

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#129] opened 2016-04-19 10:00 UTC
At the moment it is not possible to have multiple language PDFs uploaded for the Snapshots. This is problematic since we are now translating more and more of the snapshots and it would be very useful if there were at least an option to have multiple languages available for each snapshot, especially since a basic translation of title and abstract is possible.

**Comment by elondaits** [comment] 2016-04-19 12:49
duplicate of #119

**Closed by elondaits** 2016-04-19 12:49 UTC
Labels: bug, enhancement, high priority

**Comment by elondaits** [comment] 2016-04-19 12:51
Also duplicate of #98, but that issue was originally assigned to Konrad and Andreas will probably assign it to me at some point, so I'm not closing it until then.

**Comment by ppxasjsm** [comment] 2016-04-19 14:45
Ah Ok I thought there was an issue on this before. I just couldn't see it, sorry about that.
