### ISSUE TITLE
[Snapshots] Language change on edit

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#76] opened 2015-05-16 21:22 UTC
I was doing a couple of changes to the Snapshots and I noticed that with a couple of them at least, when I click on edit, the abstract appears in French. When I then click on Submit to editors and I go back to the published snapshot, everything is back in its original language (English/German). I use the Imaginary platform in English and never tried to translate/change language settings. 
I have attached a couple of screen shots from what I observe. 

Also the communicated by section seems to be off, should it not be just the author of the snapshot who appears there?

![screen shot 2015-05-16 at 22 05 54](https://cloud.githubusercontent.com/assets/3668316/7668003/ec6269c8-fc19-11e4-8a78-4a5f3cac0c88.png)
![screen shot 2015-05-16 at 22 06 04](https://cloud.githubusercontent.com/assets/3668316/7668004/ec6574b0-fc19-11e4-8ffc-df5c18c08436.png)
![screen shot 2015-05-16 at 22 06 20](https://cloud.githubusercontent.com/assets/3668316/7668007/ec8ebadc-fc19-11e4-972c-8ee52ba5d14d.png)
![screen shot 2015-05-16 at 22 07 17](https://cloud.githubusercontent.com/assets/3668316/7668006/ec8a0f82-fc19-11e4-9ebd-ce7f9b40c1ad.png)
![screen shot 2015-05-16 at 22 08 01](https://cloud.githubusercontent.com/assets/3668316/7668005/ec8a0816-fc19-11e4-9208-864090d4f32f.png)

**Comment by elondaits** [comment] 2015-07-18 15:32
@ppxasjsm , I saw this problem in action soon after you reported it, but I can't reproduce it now. I'm not sure if it was somehow fixed, if it depends on the user (though I did see it with my user at one point) or if it depends on the submission / translation state of the snapshot.

Could you please confirm if you still see it? If so, please indicate the URL of the snapshot so I can examine it.

**Comment by ppxasjsm** [comment] 2015-07-18 18:34
It appears that the snapshot is no longer on the imaginary website. I am not sure how this happened. On the MFO website it is still there. Here is the link:
http://www.mfo.de/math-in-public/snapshots/files/dirichlet-series

**Comment by elondaits** [comment] 2015-07-18 19:30
It is here, I found it through Google:

http://imaginary.org/snapshot/dirichlet-series

you can also find it by filtering by "Analysis".

**Comment by elondaits** [comment] 2015-07-18 19:34
Though you're correct in that the snapshot doesn't appear without selecting a filter. I'm going to report an extra issue with that problem.

**Comment by ppxasjsm** [comment] 2015-07-19 21:20
The snapshot does now have a proper French translation option and the languages no longer seem to be confused.

**Comment by elondaits** [comment] 2015-07-20 04:49
Since the problem seems to be gone I'm closing the issue. Feel free to reopen if you find it again.

**Closed by elondaits** 2015-07-20 04:49 UTC
Labels: bug, work in progress
