### ISSUE TITLE
Text section - individual (main) PDFs for individual languages

### ISSUE THREAD

**Issue by andreasdanielmatt** [IMAGINARY/imaginary-web#98] opened 2015-08-29 08:06 UTC
I was just about t o link to a text (crystal and maths) in the background material section, (http://imaginary.org/de/node/833) from a German web page. Would it be possible to show the German version of the PDF when German is selected? (now always the English one is shown, and the German pdf is small below). This also applies for other languages (maybe one can mark the main pdf for the respective language, default can be English).

**Comment by elondaits** [comment] 2016-04-19 13:13
Closing as duplicate of #119 which aims to centralize all requirements for changing the data model of the texts section to allow for multiple translations of PDFs.

**Closed by elondaits** 2016-04-19 13:13 UTC
Labels: enhancement
