### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#93] opened 2015-07-17 14:57 UTC
When logged in as admin, I get loooong error messages (about six times as long as visible in the screenshot).

![1](https://cloud.githubusercontent.com/assets/10153723/8749878/80e7d1e0-2ca4-11e5-91ff-9cdc3ee8d17b.jpg)

It would save me a lot of scrolling if it were changed :-)

**Comment by HexeBianca** [comment] 2015-07-17 14:59
Oh, I guess, this is already described in #92 .

**Comment by elondaits** [comment] 2015-07-17 15:39
Yes, it's a duplicate of #92 
It's a pre-existing bug in a 3rd party component that now just got visible / more annoying because of changes to the SCSS files. It only appears when the SCSS files get rebuilt, and I (mistakenly) thought it wouldn't be as frequent that you (or other collaborators) would see it... but I was mistaken.

I'll most likely will be fixing it tomorrow.

**Closed by elondaits** 2015-07-17 15:39 UTC
Labels: bug
