### ISSUE TITLE
URL-based uploads

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/imaginary-web#60] opened 2015-03-24 11:07 UTC
I have to upload a collection of binaries on a regular basis to the imaginary plattform. What really bothers me, is that I can only upload files from my local computer but not from a URL. Many of the files are already available on github and it would be much easier and especially faster to directly specify a URL for uploading. The upload speed of my local internet connection is a real bottleneck and providing the upload URL directly would save me quite a few hours per month.

**Comment by elondaits** [comment] 2015-03-24 11:22
I'm marking this as a duplicate of issue https://github.com/IMAGINARY/imaginary-web/issues/60 because both are heavily coupled and there's no sense in working on a solution to one without considering the other.
I'll add my thoughts on this issue in https://github.com/IMAGINARY/imaginary-web/issues/60.

**Closed by elondaits** 2015-03-24 11:22 UTC
Labels: duplicate, enhancement

**Comment by porst17** [comment] 2015-03-24 11:29
You probable wanted to refer to #61, not to #60 (which is reflexive). My idea was that this issue is related to the user interface, while the #61 is related to some kind of API. Nevertheless, they both do the same thing in the end.

**Comment by elondaits** [comment] 2015-03-24 11:30
Yes, my bad. Fixed it.
