### ISSUE TITLE
missing languages!

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#83] opened 2015-06-11 08:44 UTC
Fench and Korean cannot be chosen via the language selection!
![1](https://cloud.githubusercontent.com/assets/10153723/8103169/a7ccd4c6-1026-11e5-9a28-235e399c72a2.jpg)

**Comment by elondaits** [comment] 2015-06-11 14:02
They got hidden because old code was reintroduced in this week's update. I'm working on it.

**Comment by elondaits** [comment] 2015-06-11 14:49
Fixed in 568767f787b787788f2eae4f08eeb62399491bfa

We'll be making the SCSS files cleaner to avoid this kind of regression in the future.

**Closed** 2015-06-11 14:49 UTC
Labels: bug, extremely urgent, high priority
